### ISSUE TITLE
Skip-Firewall not working in unattanded mode

### ISSUE THREAD

**Issue by netzint** [linuxmuster/linuxmuster-base7#20] opened 2018-05-09 12:57 UTC
Details on: https://github.com/linuxmuster/linuxmuster-webui7/issues/12

The created ini file seams to be ok: 

[setup]
servername = server
domainname = linumxuster.lan
adminpw = a
skipfw = True > that should be ok

**Comment by zefanja** [comment] 2018-05-09 13:03
Just tested and confirmed. `skipfw = True` does not skip the firewall setup.

**Comment by HappyBasher** [comment] 2018-05-09 17:19
Fixed in 7.0.0-47.

**Closed by HappyBasher** 2018-05-09 17:19 UTC

**Comment by zefanja** [comment] 2019-01-01 04:46
In the most recent version, skipping firewall config does not work in unattended mode, because the value in the custom.ini is not checked in `linuxmuster-setup`.
